require "user.options"
require "user.keymaps"
require "user.plugins"

require "user.colorscheme"
require "user.colorscheme.nightfox"
require "user.nvim-tree"
require "user.telescope"
require "user.gitsigns"
require "user.lsp"
require "user.cmp"
require "user.dap"
require "user.bubbles"
