require "plugins.packages"
require "plugins.colorscheme"
require "plugins.nvim-tree"
require "plugins.telescope"
require "plugins.gitsigns"
require "plugins.lspconfig"
require "plugins.cmp"
require "plugins.lualine"
