require "plugins.packages"
require "plugins.colorscheme"
-- require "plugins.nvim-tree"
require "plugins.telescope"
require "plugins.gitsigns"
require "plugins.cmp"
require "plugins.lualine"
require "plugins.bufferline"
require "plugins.neo-tree"
require "plugins.dap"
-- require "plugins.neorg"
require "plugins.mason"
require "plugins.mason-lspconfig"
require "plugins.lspconfig"
require "plugins.lspsaga"

require "plugins.noice"
